title: Killian Cimino # your name (or website title) here
logo: "images/HeadShotCircle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Analyst with one year of job experience. I've previously worked for Vroom and the Amazon Labor Union. I have experience using a variety of techniques to analyze data, and I am always excited to learn more. I enjoy solving complex problems, often using visualizations which help to present complicated data in an accessible manner. 
  <br><br>

  <a href="https://www.linkedin.com/in/killian-cimino/">View My LinkedIn Profile</a> 
  <br> 
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
