title: Kathleen Cimino # your name (or website title) here
logo: "images/HeadShotCircle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Senior at Wesleyan University and a Data Analyst for the Amazon Labor Union. I have experience using a variety of techniques to analyze data, and I am always excited to learn more. I enjoy explaining to people what insights they can gain from the data, often using visualizations which help to present complicated data in an accessible manner. 
  <br><br>

  <a href="https://www.linkedin.com/in/kathleen-cimino/">View My LinkedIn Profile</a> 
<br><br>  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
